import Head from 'next/head'
import { Inter } from 'next/font/google'
import Header from '../../components/global/Header'
import Hero from '../../components/home/Hero'
import BusinessOwners from '../../components/home/AboutMunch'
import Banner from '../../components/home/Banner'
import QuickLinks from '../../components/home/QuickLinks'
import Testimonials from '../../components/home/Testimonials'
import Footer from '../../components/global/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative flex flex-col">
        <Header />
        <Hero />
        <Banner />
        <QuickLinks />
        <BusinessOwners />
        <Footer />
      </main>
    </>
  )
}
